name: Release Notification

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  workflow_run:
    workflows: ["Auto compile with openwrt sdk"]
    types:
      - completed

jobs:
  notify-on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          wget https://github.com/rtaserver/openwrt-passwall2/releases/download/1.24-1/luci-23.05_luci-app-passwall2_1.24-1_all.ipk
          curl -F "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" -F "caption=Yo" -F "document=luci-23.05_luci-app-passwall2_1.24-1_all.ipk" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
