name: Release Notification

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  workflow_run:
    workflows: ["Auto compile with openwrt sdk"]
    types:
      - completed

jobs:
  notify-on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          CHAT_ID='${{ secrets.TELEGRAM_CHAT_ID }}'
          BOT_TOKEN='${{ secrets.TELEGRAM_TOKEN }}'

          # ngeping, klo berhasil lanjut, klo gagal restart modem dan nunggu on modem, lalu lanjut looping lg.

          log_file="/tmp/log.txt"
          destination="/root/log_archive/"

          echo "Waktu: $(date +"%d-%m-%Y %H:%M:%S")" >> $log_file

          # SEND LOGS TO TELEGRAM
          MSG="DONE✅"
          curl -F "chat_id=$CHAT_ID" -F "caption=$MSG" -F "document=$log_file" \
          https://api.telegram.org/bot$BOT_TOKEN/sendDocument
